// Generated by CoffeeScript 1.7.1
(function() {
  var EXTENSION;

  EXTENSION = require('./2-EXTENSION');

  this.parse = function(text) {
    return EXTENSION.expression.run(text);
  };

}).call(this);
